swagger: '2.0'
info:
  title: Tagallery
  description: Tag based image gallery.
  version: 1.0.0
schemes:
  - http
  - https
basePath: /v1
produces:
  - application/json
paths:
  /tags:
    get:
      summary: List of tags
      description: Return the list of tags in the system
      parameters:
        - name: filter
          in: query
          description: Return tags that start with the string.
          required: false
          type: string
      tags:
        - Tags
      responses:
        '200':
          description: List of tags
          schema:
            type: array
            items:
              $ref: '#/definitions/Tag'
    post:
      summary: Create a new tag.
      description: Creates a new tag and return its ID.
      parameters:
        - name: name
          in: body
          description: The name of the tag.
          required: true
          schema:
            type: string
      tags:
        - Tags
      responses:
        '200':
          description: Tag was created.
          schema: 
            $ref: '#/definitions/Tag'
  /tags/{id}:
    get:
      summary: Retrieve a tag.
      description: Retrieve the information of a single tag.
      parameters:
        - name: id
          in: path
          description: ID of the tag to be retrieved.
          required: true
          type: number
      tags:
        - Tags
      responses:
        '200':
          description: Tag information.
          schema:
            $ref: '#/definitions/Tag'
        '400':
          description: Tag doesn't exist.
    put:
      summary: Update a tag.
      description: Update the information of a tag.
      parameters:
        - name: id
          in: path
          description: ID of the tag to be changed.
          required: true
          type: number
        - name: name
          in: body
          description: New description of the tag.
          required: true
          schema:
            type: string
      tags:
        - Tags
      responses:
        '200':
          description: New tag information.
          schema:
            $ref: '#/definitions/Tag'
        '400':
          description: Tag doesn't exist.
    delete:
      summary: Delete a tag.
      description: |
        Deletes a tag from the system. 
        Images associated with the tag are not changed.
      parameters:
        - name: id
          in: path
          description: ID of the tag to be removed.
          required: true
          type: number
      responses:
        '200':
          description: Tag deleted.
        '400':
          description: Tag doesn't exist.
      

definitions:
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string